#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes;

my $reporting_interval = 1.0; # seconds
my $bytes_this_interval = 0;
my $start_time = [Time::HiRes::gettimeofday()];

STDOUT->autoflush(1);

while (<>) {
  if (/ length (\d+):/) {
    $bytes_this_interval += $1;
    my $elapsed_seconds = Time::HiRes::tv_interval($start_time);
    if ($elapsed_seconds > $reporting_interval) {
       my $bps = $bytes_this_interval / $elapsed_seconds;
       #printf "%02d:%02d:%02d %10.2f Bps\n", (localtime())[2,1,0],$bps;
       
    
       printf "%04d/%02d/%02d %02d:%02d:%02d %10.2fBps\n", (((localtime())[5]+1900),((localtime())[4]+1),(localtime())[3,2,1,0],$bps); # ook met extra haakjes er rond

       #$datestring = localtime();
	   #print "$datestring ";

       #printf("%10.2f Bps\n",$bps);
       $start_time = [Time::HiRes::gettimeofday()];
       $bytes_this_interval = 0;
    }
  }
}